### ISSUE TITLE
XML documentation of all public Nickel methods

### ISSUE THREAD

**Issue by Shockah** [Shockah/Nickel#33]

**Comment by Shockah** [comment]
At the same time, a PR doing this should enable a linting rule to warn about any missing documentation for public members.

**Comment by Fayti1703** [comment]
Would it be possible to annotate the public members somehow (e.g. with a [`JetBrains.Annotations`](https://www.nuget.org/packages/JetBrains.Annotations)`.PublicAPI` attribute)? That would help with getting an overview of what needs to be documented.

**Comment by Shockah** [comment]
It's essentially all types which are public, and all public members of said types.

**Comment by Fayti1703** [comment]
> At the same time, a PR doing this should enable a linting rule to warn about any missing documentation for public members.

Looking into this, it turns out MSBuild property `GenerateDocumentationFile` (which enables generating an `.xml` file with the documentation extracted) automatically enables the built-in warning for missing documentation on public types ([`CS1591`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591)).

(`dotnet format` does not display these, however. If we want a warning on PRs, that will require separate setup.)

**Comment by Shockah** [comment]
Done in upcoming Nickel 1.0.0. The warning for missing docs is not yet setup.
